config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :bookmarks, :lists
  resources :lists do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path, status: :see_other
  end

  private

  # def set_list
  #   @list = List.find(params[:list_id])
  # end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container py-5">
<h1>Add a bookmark</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
  <%= f.association :movie, prompt: "Select a movie", input_html: {data: { controller: "tom-select"}} %>
  <%= f.submit class: "btn btn-flat border" %>
<% end %>

<%= link_to "Back to list", lists_path, class: "btn btn-success mt-3" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://images.unsplash.com/photo-1585647347483-22b66260dfff?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cG9wY29ybnxlbnwwfDB8MHx8fDA%3D&auto=format&fit=crop&w=1000&q=60" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "My lists", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New list", new_list_path, class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>
</div>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1595769816263-9b910be24d5f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Y2luZW1hfGVufDB8MHwwfHx8MA%3D%3D&auto=format&fit=crop&w=1000&q=60);">
  <div class="container">
    <h1 class="text-center">Save any kind of movies</h1>
    <p class="text-center">Classic</p>
    <a class="btn btn-flat" href="#">Apply now</a>
  </div>
</div>
<div class="mt-5">
<h1 class="fw-bold ms-5">My lists</h1>

<ul class="card-list">
  <% @lists.each do |list| %>
    <div class="card-category mt-2 w-25 mx-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://plus.unsplash.com/premium_photo-1676573201174-75d318b983e8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8dGl0YW5pY3xlbnwwfDB8MHx8fDA%3D&auto=format&fit=crop&w=1000&q=60)">
    <li><%= link_to list.name, list_path(list.id), class: "text-decoration-none" %></li>
    </div>
  <% end %>
</ul>
<div class="d-flex justify-content-center">
<%= link_to "Create a movie list", new_list_path, class: "btn btn-success text-white fw-bold" %>
</div>
</div>

app/views/lists/new.html.erb
<div class="container d-flex justify-content-center py-5">
  <div class="row">
    <div class="col-12">
      <div class="bg-white rounded p-4 shadow">
        <h3>Create a new list</h3>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: '...' %>
          <%= f.submit class: 'btn btn-flat border' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= link_to "Back to list", lists_path, class: "ms-4 text-decoration-none btn btn-success text-white fw-bold" %>

app/views/lists/show.html.erb
<div class="container py-5">
<h1>Show</h1>

<h2><%= @list.name %></h2>

<ul>
<%= @list.bookmarks.each do |movie| %>
  <li><%= bookmark.movie.title %></li>
  <li><%= bookmark.movie.overview %></li>
<% end %>
</ul>

<%= link_to "Add a bookmark", new_bookmark_path, class: "text-decoration-none btn btn-success text-white fw-bold" %>
<br>
<%= link_to "Go back", lists_path, class: "text-decoration-none btn btn-success text-white fw-bold mt-3" %>
</div>